from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)


DECISIONS = {
    "SHORTLISTED",
    "REVIEW",
    "REJECTED",
}


def load_day14_results(
    input_dir: str | Path,
) -> list[dict[str, Any]]:
    """
    Load candidate ranking results generated by Day 14.
    """

    input_dir = Path(input_dir)

    records = []

    if not input_dir.exists():
        raise FileNotFoundError(
            f"Day 14 output directory not found: {input_dir}"
        )

    for file_path in sorted(
        input_dir.glob("JOB*_ranked_candidates.json")
    ):

        with open(
            file_path,
            "r",
            encoding="utf-8",
        ) as file:

            data = json.load(file)

        job_id = data.get(
            "job_id",
            "",
        )

        job_title = data.get(
            "job_title",
            "",
        )

        candidates = data.get(
            "ranked_candidates",
            [],
        )

        if not isinstance(
            candidates,
            list,
        ):
            continue

        for candidate in candidates:

            if not isinstance(
                candidate,
                dict,
            ):
                continue

            records.append(
                {
                    "job_id": job_id,
                    "job_title": job_title,
                    "candidate_name": candidate.get(
                        "candidate_name",
                        "",
                    ),
                    "ai_score": float(
                        candidate.get(
                            "final_ats_score",
                            0.0,
                        )
                    ),
                    "ai_decision": candidate.get(
                        "decision",
                        "UNKNOWN",
                    ),
                    "ai_rank": candidate.get(
                        "rank"
                    ),
                }
            )

    return records


def create_manual_review_template(
    records: list[dict[str, Any]],
    output_file: str | Path,
) -> None:
    """
    Create a manual review CSV.

    Human reviewer fills:
        manual_decision
        profile_category
        review_notes
    """

    output_file = Path(output_file)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fieldnames = [
        "job_id",
        "job_title",
        "candidate_name",
        "ai_score",
        "ai_decision",
        "ai_rank",
        "manual_decision",
        "profile_category",
        "review_notes",
    ]

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        for record in records:

            writer.writerow(
                {
                    "job_id": record.get(
                        "job_id",
                        "",
                    ),
                    "job_title": record.get(
                        "job_title",
                        "",
                    ),
                    "candidate_name": record.get(
                        "candidate_name",
                        "",
                    ),
                    "ai_score": record.get(
                        "ai_score",
                        0.0,
                    ),
                    "ai_decision": record.get(
                        "ai_decision",
                        "",
                    ),
                    "ai_rank": record.get(
                        "ai_rank",
                        "",
                    ),
                    "manual_decision": "",
                    "profile_category": "",
                    "review_notes": "",
                }
            )


def load_manual_review(
    review_file: str | Path,
) -> list[dict[str, Any]]:

    review_file = Path(review_file)

    if not review_file.exists():

        raise FileNotFoundError(
            f"Manual review file not found: {review_file}"
        )

    with open(
        review_file,
        "r",
        newline="",
        encoding="utf-8",
    ) as file:

        reader = csv.DictReader(file)

        records = list(reader)

    return records


def validate_manual_review(
    records: list[dict[str, Any]],
) -> None:
    """
    Validate manual review records.
    """

    errors = []

    for index, record in enumerate(
        records,
        start=2,
    ):

        manual_decision = (
            str(
                record.get(
                    "manual_decision",
                    "",
                )
            )
            .strip()
            .upper()
        )

        category = (
            str(
                record.get(
                    "profile_category",
                    "",
                )
            )
            .strip()
            .lower()
        )

        if manual_decision not in DECISIONS:

            errors.append(
                f"Row {index}: invalid manual_decision"
            )

        if not category:

            errors.append(
                f"Row {index}: profile_category is empty"
            )

    if errors:

        message = "\n".join(errors)

        raise ValueError(
            "Manual review validation failed:\n"
            + message
        )


def merge_ai_and_manual_results(
    ai_records: list[dict[str, Any]],
    manual_records: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    manual_lookup = {}

    for record in manual_records:

        key = (
            str(
                record.get(
                    "job_id",
                    "",
                )
            )
            .strip(),

            str(
                record.get(
                    "candidate_name",
                    "",
                )
            )
            .strip()
            .lower(),
        )

        manual_lookup[key] = record

    merged = []

    for ai_record in ai_records:

        key = (
            str(
                ai_record.get(
                    "job_id",
                    "",
                )
            )
            .strip(),

            str(
                ai_record.get(
                    "candidate_name",
                    "",
                )
            )
            .strip()
            .lower(),
        )

        manual = manual_lookup.get(key)

        if manual is None:
            continue

        merged.append(
            {
                **ai_record,

                "manual_decision": (
                    str(
                        manual.get(
                            "manual_decision",
                            "",
                        )
                    )
                    .strip()
                    .upper()
                ),

                "profile_category": (
                    str(
                        manual.get(
                            "profile_category",
                            "",
                        )
                    )
                    .strip()
                    .lower()
                ),

                "review_notes": manual.get(
                    "review_notes",
                    "",
                ),
            }
        )

    return merged


def calculate_metrics(
    records: list[dict[str, Any]],
) -> dict[str, Any]:

    if not records:
        raise ValueError(
            "No records available for metric calculation."
        )

    # Positive class:
    # SHORTLISTED and REVIEW are considered candidates
    # that should not be rejected.
    #
    # Negative class:
    # REJECTED

    positive_decisions = {
        "SHORTLISTED",
        "REVIEW",
    }

    y_true = [
        1
        if record["manual_decision"] in positive_decisions
        else 0
        for record in records
    ]

    y_pred = [
        1
        if record["ai_decision"] in positive_decisions
        else 0
        for record in records
    ]

    accuracy = accuracy_score(
        y_true,
        y_pred,
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0,
    )

    matrix = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1],
    )

    true_negative = int(
        matrix[0][0]
    )

    false_positive = int(
        matrix[0][1]
    )

    false_negative = int(
        matrix[1][0]
    )

    true_positive = int(
        matrix[1][1]
    )

    return {
        "total_cases": len(records),
        "accuracy": round(
            float(accuracy),
            4,
        ),
        "precision": round(
            float(precision),
            4,
        ),
        "recall": round(
            float(recall),
            4,
        ),
        "f1_score": round(
            float(f1),
            4,
        ),
        "true_positive": true_positive,
        "true_negative": true_negative,
        "false_positive": false_positive,
        "false_negative": false_negative,
    }


def find_mismatches(
    records: list[dict[str, Any]],
) -> list[dict[str, Any]]:

    mismatches = []

    for record in records:

        if (
            record["ai_decision"]
            != record["manual_decision"]
        ):

            mismatches.append(
                {
                    "job_id": record["job_id"],
                    "job_title": record["job_title"],
                    "candidate_name": record[
                        "candidate_name"
                    ],
                    "ai_score": record["ai_score"],
                    "ai_decision": record[
                        "ai_decision"
                    ],
                    "manual_decision": record[
                        "manual_decision"
                    ],
                    "profile_category": record[
                        "profile_category"
                    ],
                    "review_notes": record[
                        "review_notes"
                    ],
                }
            )

    return mismatches


def calculate_category_metrics(
    records: list[dict[str, Any]],
) -> dict[str, Any]:

    categories = {}

    for record in records:

        category = record[
            "profile_category"
        ]

        categories.setdefault(
            category,
            [],
        ).append(record)

    results = {}

    for category, category_records in categories.items():

        results[category] = calculate_metrics(
            category_records
        )

    return results


def save_json(
    output_file: str | Path,
    data: dict[str, Any],
) -> None:

    output_file = Path(output_file)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        output_file,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            data,
            file,
            indent=4,
            ensure_ascii=False,
        )


def save_mismatches(
    output_file: str | Path,
    mismatches: list[dict[str, Any]],
) -> None:

    output_file = Path(output_file)

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fieldnames = [
        "job_id",
        "job_title",
        "candidate_name",
        "ai_score",
        "ai_decision",
        "manual_decision",
        "profile_category",
        "review_notes",
    ]

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        writer.writerows(
            mismatches
        )