DEGREE_PATTERNS = {
    "PHD": [
        "phd",
        "ph.d",
        "doctor of philosophy",
    ],
    "MASTER": [
        "m.sc",
        "msc",
        "m.s",
        "ms",
        "m.a",
        "ma",
        "m.com",
        "mcom",
        "mba",
        "m.tech",
        "mtech",
        "master of science",
        "master of arts",
        "master of commerce",
        "master of business administration",
        "master of technology",
    ],
    "BACHELOR": [
        "b.sc",
        "bsc",
        "b.s",
        "bs",
        "b.a",
        "ba",
        "b.com",
        "bcom",
        "bba",
        "b.tech",
        "btech",
        "b.e",
        "be",
        "b.des",
        "bdes",
        "bachelor of science",
        "bachelor of arts",
        "bachelor of commerce",
        "bachelor of business administration",
        "bachelor of technology",
        "bachelor of design",
    ],
    "DIPLOMA": [
        "diploma",
        "polytechnic",
    ],
    "HIGH_SCHOOL": [
        "higher secondary",
        "secondary school",
        "high school",
        "12th",
        "10th",
    ],
}


CERTIFICATION_CATEGORIES = {
    "TECHNICAL": [
        "aws",
        "azure",
        "google cloud",
        "gcp",
        "python",
        "sql",
        "machine learning",
        "data science",
        "data analytics",
        "power bi",
        "tableau",
        "tensorflow",
        "cisco",
        "comptia",
    ],
    "BUSINESS": [
        "project management",
        "pmp",
        "scrum",
        "agile",
        "six sigma",
        "business analysis",
    ],
    "CREATIVE": [
        "ux design",
        "ui design",
        "graphic design",
        "adobe",
        "photoshop",
        "illustrator",
        "figma",
    ],
    "LANGUAGE": [
        "ielts",
        "toefl",
        "english proficiency",
    ],
}


FIELD_NORMALIZATION = {
    "data science and analytics": "Data Science",
    "data science": "Data Science",
    "computer science": "Computer Science",
    "computer applications": "Computer Applications",
    "information technology": "Information Technology",
    "information systems": "Information Systems",
    "business administration": "Business Administration",
    "business management": "Business Management",
    "mechanical engineering": "Mechanical Engineering",
    "civil engineering": "Civil Engineering",
    "electrical engineering": "Electrical Engineering",
    "electronics engineering": "Electronics Engineering",
    "communication design": "Communication Design",
    "graphic design": "Graphic Design",
    "marketing": "Marketing",
    "finance": "Finance",
    "human resources": "Human Resources",
}